---
- name: Install developer general tools
  ansible.builtin.package:
    name:
      - curl
      - flatpak
      - jq
      - net-tools
      - strace
      - telnet
      - wget
    state: latest
  become: true

- name: Install developer toolchains
  ansible.builtin.package:
    name:
      - gcc
      - gcc-c++
      - gdb
      - valgrind
      - make
      - cmake
    state: latest
  become: true

- name: Install developer libraries
  ansible.builtin.package:
    name:
      - gtest-devel
      - gnutls-devel
      - libxdg-basedir-devel
      - SDL2-devel
      - SDL2_image-devel
      - SDL2_mixer-devel
      - SDL2_net-devel
      - SDL2_ttf-devel
      - GLee-devel
      - freetype-devel
      - libxml2-devel
    state: latest
  become: true


- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install developer flatpak tools
  community.general.flatpak:
    name:
      - com.obsproject.Studio
      - org.audacityteam.Audacity
      - org.inkscape.Inkscape
    state: latest
    method: user
