---
- ansible.builtin.include_tasks: setup-bash.yml

- ansible.builtin.include_tasks: install-software.yml

- ansible.builtin.include_tasks: setup-git.yml

- name: Create dev directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Documents/dev"
    state: directory
    mode: '770'
