---
- include_tasks: setup-bash.yml

- include_tasks: install-software.yml

- include_tasks: setup-git.yml

- name: Create dev directory
  file:
    path: "{{ ansible_env.HOME }}/Documents/dev"
    state: directory
