---
- name: Keep a longer bash history
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
  loop:
    - "export HISTSIZE=100000"
    - "export HISTFILESIZE=1000000"
    - "export HISTTIMEFORMAT=\"%F %T \""
    - "shopt -s histappend"
