---
- name: Install developer general tools
  package:
    name:
      - git
      - vim
    state: latest
  become: true

# SSH keys
- name: Create .ssh directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0740

- name: Copy the certificate to the host
  copy:
    content: '{{ git_certificate }}'
    dest: "{{ ansible_env.HOME }}/.ssh/github_id_rsa.pub"
    mode: 0644

- name: Copy the private key to the host
  copy:
    content: '{{ git_private_key }}'
    dest: "{{ ansible_env.HOME }}/.ssh/github_id_rsa"
    mode: 0600
  no_log: true


# User configuration
- name: Set email
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: user.name, value: "{{ git_config_user_name }}" }
    - { name: user.email, value: "{{ git_config_email }}" }
    - { name: pull.rebase, value: false }
    - { name: push.autoSetupRemote, value: true }
    - { name: init.defaultBranch, value: main }
    - { name: color.ui, value: auto }
    - { name: core.editor, value: vim }
