---
- name: Keep a longer bash history
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: "{{ item }}"
  loop:
    - "export HISTSIZE=100000"
    - "export HISTTIMEFORMAT=\"%F %T \""
