---
- name: Keep a longer bash history
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
  loop:
    - "export HISTSIZE=100000"
    - "export HISTFILESIZE=1000000"
    - "export HISTTIMEFORMAT=\"%F %T \""
    - "shopt -s histappend"
    - "export EDITOR=vim" # For git
    - "export GPG_TTY=$(tty)" # For GPG key access
    - "export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id --user)/bus" # For systemctl user service access
