---
- name: Create the ssl folder for Home Assistant
  ansible.builtin.file:
    path: "{{ home_assistant_volumes_basedir }}/config/ssl"
    owner: "{{ home_assistant_container_user }}"
    group: "{{ home_assistant_container_group }}"
    state: directory
    mode: '0700'

- name: Install the public certificate
  ansible.builtin.template:
    src: fullchain.pem.j2
    dest: "{{ home_assistant_volumes_basedir }}/config/ssl/fullchain.pem"
    owner: "{{ home_assistant_container_user }}"
    group: "{{ home_assistant_container_group }}"
    mode: 0600
  register: home_assistant_public_key_copy

- name: Install the private key
  ansible.builtin.template:
    src: privkey.pem.j2
    dest: "{{ home_assistant_volumes_basedir }}/config/ssl/privkey.pem"
    owner: "{{ home_assistant_container_user }}"
    group: "{{ home_assistant_container_group }}"
    mode: 0600
  register: home_assistant_private_key_copy

- name: Set Home Assistant restart
  set_fact:
    home_assistant_restart: true
  when: home_assistant_public_key_copy.changed or home_assistant_private_key_copy.changed
