---
- name: Create the ssl folder for Home Assistant
  file:
    path: "{{ home_assistant_volumes_basedir }}/config/ssl"
    owner: "{{ home_assistant_container_user }}"
    group: "{{ home_assistant_container_group }}"
    state: directory

- name: Install the public certificate
  template:
    src: fullchain.pem.j2
    dest: "{{ home_assistant_volumes_basedir }}/config/ssl/fullchain.pem"
    owner: "{{ home_assistant_container_user }}"
    group: "{{ home_assistant_container_group }}"
    mode: 0600

- name: Install the private key
  template:
    src: privkey.pem.j2
    dest: "{{ home_assistant_volumes_basedir }}/config/ssl/privkey.pem"
    owner: "{{ home_assistant_container_user }}"
    group: "{{ home_assistant_container_group }}"
    mode: 0600
