---
- block:
  - name: Copy gitlab-runner config.toml
    template:
      src: config.toml.j2
      dest: /srv/gitlab-runner/config/config.toml
      owner: root
      group: root
      mode: 770
    notify: Restart gitlab-runner container

  # TODO: Move this to an ansible vault
  - name: Copy gitlab-runner self-signed certificate
    ansible.builtin.copy:
      src: "{{ gitlab_fqdn }}.crt"
      dest: /srv/gitlab-runner/certs/
      owner: root
      group: root
      mode: '0644'
    notify: Restart gitlab-runner container

  # Returns output something like "gitlab/gitlab-runner:v16.4.2"
  - name: Get gitlab-runner version
    command: docker inspect --format=\'\{\{\.Config\.Image\}\}\' gitlab-runner
    register: gitlab_runner_inspect_version

  become: true

# NOTE: We use an assert purely as a place holder to check if the gitlab runner version is different and notify the handler 
- name: Restart gitlab-runner if new version
  assert: { that: true, quiet: true }
  when: gitlab_runner_inspect_version.stdout != "gitlab/gitlab-runner:v" + gitlab_runner_version
  notify: Restart gitlab-runner container
