---
stages:
  - tests-and-checks

default:
  before_script:
    - dnf install -y ansible yamllint python3-ansible-lint ansible-collection-containers-podman

check-yaml:
  stage: tests-and-checks
  tags:
    - linux
  script:
    - yamllint -c .yamllint .

check-ansible:
  stage: tests-and-checks
  tags:
    - linux
  script:
    - ANSIBLE_CONFIG=ansible.cfg ansible-lint
