---
# Samba share
fileserver_network_home_samba_folder: /data1
fileserver_network_home_samba_username: chris
#\\192.168.0.84\data

# Gitlab
gitlab_fqdn: gitlab.network.home
gitlab_https_port: 2443
gitlab_url: "https://{{ gitlab_fqdn }}:{{ gitlab_https_port }}/"
gitlab_registry_port: 5050
gitlab_container_registry_user: chris # For access to the gitlab container registry from another host (For podman to login to the gitlab registry and pull images)

# Home Assistant
# Change these to suit your location
home_assistant_timezone: Australia/Sydney
home_assistant_location_latitude: -33.86785000
home_assistant_location_longitude: 151.20732000
home_assistant_location_elevation: 40

# StirlingPDF
stirlingpdf_fqdn: pdf.network.home

# syslog-ng
syslogng_fqdn: syslog.network.home
syslogng_server_port: 514 # I would use a non-standard port, but selinux complains, so it is either this or add an selinux rule to add an extra port to logger_t

# Tandoor Recipes
tandoor_fqdn: tandoor.network.home

# Task-tracker
tasktracker_fqdn: tasktracker.network.home

# Vaultwarden
vaultwarden_fqdn: vaultwarden.network.home
