---
# Samba share
fileserver_network_home_samba_folder: /data1
fileserver_network_home_samba_username: chris
#\\192.168.0.84\data

# Gitlab
gitlab_fqdn: gitlab.network.home
gitlab_https_port: 2443
gitlab_url: "https://{{ gitlab_fqdn }}:{{ gitlab_https_port }}/"
gitlab_registry_port: 5050

# Home Assistant
# Change these to suit your location
home_assistant_timezone: Australia/Sydney
home_assistant_location_latitude: -33.86785000
home_assistant_location_longitude: 151.20732000
home_assistant_location_elevation: 40

# StirlingPDF
stirlingpdf_fqdn: pdf.network.home

# Tandoor Recipes
tandoor_fqdn: tandoor.network.home

# Vaultwarden
vaultwarden_fqdn: vaultwarden.network.home
