---
# Gitlab
#
# Version Upgrade Warning
#
# WARNING: For an existing instance you can't just pick the latest gitlab version and run it,
# you have to follow the recommanded gitlab upgrade paths, which basically means installing certain intermediate versions
# that will modify your install user data to work with the new version.
# Otherwise, if you update from 14.10.5 straight to 16.3.0 for example it may not be able to interpret your data as it is
# expecting a 15.x.y version of the data. So don't just blindly upgrade, follow the upgrade path set out below.
#
# Upgrade Paths
# https://docs.gitlab.com/ee/update/upgrade_paths.html
#
# 15.0.5 > 15.4.6 > 15.11.13
# 16.1 > 16.3.7 > 16.7.7 > 16.11.10
# 17.1.8 > 17.3.7 > 17.5.z. The latest GitLab 17.5 release.
#
# What versions are available? This is a quick way to find out:
# https://hub.docker.com/r/gitlab/gitlab-ce/tags?page=1
#
# Upgrade Process
#
# As the gitlab container user:
# systemctl --user stop gitlab-container
# (cd srv && zip -r gitlab20231101b.zip ./gitlab)
# <edit the gitlab image version in ansible, making the version jumps above>
# ansible-playbook -i inventories/network_home.ini -l chris_linux_computer -v -kK playbooks/setup-podman-and-services.yml && date && sleep 600
# <the sleep is to force waiting before running the next upgrade so that gitlab can get up and running, upgrade anything it needs to and settle down before you run the next upgrade. While you are waiting browse around, make sure your data looks to be present, check the logs to make sure everything is working properly>
gitlab_version: 16.11.10

# Gitlab runner
# NOTE: These don't necessarily match the Gitlab server version https://hub.docker.com/r/gitlab/gitlab-runner/tags
gitlab_runner_version: 16.11.1

home_assistant_version: 2024.12
stirlingpdf_version: latest-ultra-lite
tandoor_version: 1.5.17

# Vaultwarden
# https://github.com/dani-garcia/vaultwarden/releases
vaultwarden_version: 1.30.5
