---
- block:
  - name: Copy vscodium gpg key
    ansible.builtin.copy:
      src: vscodium-pub.gpg
      dest: /etc/pki/rpm-gpg/
      owner: root
      group: root
      mode: '0644'

  - name: Add vscodium yum repo
    ansible.builtin.yum_repository:
      name: vscodium
      description: vscodium
      #baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
      baseurl: https://download.vscodium.com/rpms/
      gpgcheck: 1
      repo_gpgcheck: 1
      gpgkey: file:///etc/pki/rpm-gpg/vscodium-pub.gpg
      metadata_expire: 1h

  - name: Install vscodium
    ansible.builtin.package:
      name:
        - codium
      state: latest

  become: true
