---
# Remove "hp-uiscan" and "HPLIP Graphic Tools" which were added to Fedora Workstation and Silverblue for some reason, I guess to help with printing?
# https://github.com/fedora-silverblue/issue-tracker/issues/646 (For ostree, but workstation has the same issue)
- name: Remove hp-uiscan and HPLIP Graphic Tools
  ansible.builtin.package:
    name:
      - "{{ item }}"
    state: absent
  become: true
  with_items:
    - hplip
    - hplip-gui


- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak software
  community.general.flatpak:
    name:
      #- com.vscodium.codium
      - org.gimp.GIMP
      - org.gnome.gedit
      - org.darktable.Darktable
      - org.gnome.Boxes
      - org.gnome.Rhythmbox3
      - org.mozilla.Thunderbird
      - org.signal.Signal
      - org.videolan.VLC
      - tv.kodi.Kodi
    state: present
    method: user


- ansible.builtin.include_tasks: install-firefox.yml


# Games
- block:
  # NOTE: The Steam flatpak requires quite some extra packages and configuration, so I went with the dnf version instead. Maybe next time.
  # TODO: When Selfless Heros provides a flatpak add it here https://github.com/felicien-brochu/selflessheroes/issues/19
  - name: Install flatpak games
    community.general.flatpak:
      name:
        #- com.valvesoftware.Steam
        - com.endlessnetwork.passage
        - com.endlessnetwork.aqueducts
      state: present
      method: user

  - name: Install Steam
    ansible.builtin.package:
      name: steam
      state: latest
    become: true

  when: "'gaming' in group_names"
