---
- name: Install flatpak
  package:
    name:
      - flatpak
  become: true

# TODO: When Selfless Heros provides a flatpak add it here
- name: Install flatpak games
  community.general.flatpak:
    name:
      - com.valvesoftware.Steam
      - com.endlessnetwork.passage
      - com.endlessnetwork.aqueducts
    state: present
    method: user
