---
# NOTE: libva-utils is for ffmpeg
- name: Install libva-utils for ffmpeg
  package:
    name:
      - libva-utils
    state: latest
  become: true

# Remove the RPM version of firefox (We only want to use the flatpak version after it is installed)
- name: Remove firefox
  package:
    name:
      - firefox
    state: absent
  become: true

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

# NOTE: ffmpeg is for firefox
- name: Install flatpak software
  community.general.flatpak:
    name:
      - runtime/org.freedesktop.Platform.ffmpeg-full/x86_64/23.08 # NOTE: There are multiple versions and we have to pick a specific version
      - org.gimp.GIMP
      - org.gnome.gedit
      - org.mozilla.firefox
      - org.darktable.Darktable
      - org.gnome.Rhythmbox3
      - org.mozilla.Thunderbird
      - org.videolan.VLC
    state: present
    method: user

# TODO: When Selfless Heros provides a flatpak add it here
- name: Install flatpak games
  community.general.flatpak:
    name:
      - com.valvesoftware.Steam
      - com.endlessnetwork.passage
      - com.endlessnetwork.aqueducts
    state: present
    method: user
