---
- block:
  # Create a Fedora docker image with some development tools already installed
  - name: Copy Fedora development Dockerfile
    ansible.builtin.template:
      src: Dockerfile-fedora-development.j2
      dest: /srv/containers/fedora-development/Dockerfile
      owner: root
      group: root
      mode: '0644'
    register: dockerfile_status

  # Build the Fedora docker image
  # docker build --tag fedora-development:latest .
  - name: Build fedora-development image
    community.docker.docker_image:
      name: "{{ gitlab_runner_executor_docker_image }}"
      build:
        path: /srv/containers/fedora-development
      source: build
      state: present
      force_source: "{{ dockerfile_status.changed | default(omit) }}" # HACK: docker_image doesn't have a "state: latest" so we can't ensure it gets rebuilt, so we have to force it to get rebuilt when we know the dockerfile has changed

  become: true
