---
- block:
  - name: Copy gitlab-runner config.toml
    ansible.builtin.template:
      src: config.toml.j2
      dest: /srv/gitlab-runner/config/config.toml
      owner: root
      group: root
      mode: '0770'
    notify: Restart gitlab-runner container

  - name: Copy gitlab-runner self-signed certificate
    ansible.builtin.template:
      src: gitlab-server.crt.j2
      dest: "/srv/gitlab-runner/certs/{{ gitlab_fqdn }}.crt"
      owner: root
      group: root
      mode: '0644'
    notify: Restart gitlab-runner container

  # Returns output something like "gitlab/gitlab-runner:v16.4.2"
  - name: Get gitlab-runner version
    ansible.builtin.command: docker inspect --format=\'\{\{\.Config\.Image\}\}\' gitlab-runner
    ignore_errors: true
    register: gitlab_runner_inspect_version

  become: true

# NOTE: We use an assert purely as a place holder to check if the gitlab runner was not already running and notify the handler
- name: Start gitlab-runner if it isn't running
  ansible.builtin.assert: { that: true, quiet: true }
  changed_when: true
  when: gitlab_runner_inspect_version.rc != 0
  notify: Restart gitlab-runner container

# NOTE: We use an assert purely as a place holder to check if the gitlab runner version is different and notify the handler
- name: Restart gitlab-runner if new version
  ansible.builtin.assert: { that: true, quiet: true }
  changed_when: true
  when: gitlab_runner_inspect_version.stdout != "gitlab/gitlab-runner:v" + gitlab_runner_version
  notify: Restart gitlab-runner container
