---
- name: Create a systemd service for the container
  vars:
    service_file_name: "podman-{{ container_name }}.service"
    container_stop_timeout: 30
  block:
    - name: Generate systemd units with podman
      ansible.builtin.command:
        cmd: podman generate systemd -f -n -t "{{ container_stop_timeout }}" "{{ container_name }}"
        chdir: "/etc/systemd/system"

    - name: Check that generated service unit exists
      ansible.builtin.stat:
        path: "/etc/systemd/system/{{ service_file_name }}"
      register: stat_result

    - name: Enable systemd service unit
      ansible.builtin.systemd:
        name: "{{ service_file_name }}"
        state: started
        daemon_reload: true
        enabled: yes
      when: stat_result.stat.exists
