---
- block:
  - name: Install firewalld and podman
    ansible.builtin.package:
      name:
        - firewalld
        - podman
        - podman-compose
        - slirp4netns
      state: latest

  become: true
