---
# NOTE: We use listen to run multiple handlers at once
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html#naming-handlers
- name: Restart gitlab-runner shell block
  block:
    - name: Stop gitlab-runner shell
      ansible.builtin.command:
        cmd: "gitlab-runner stop"
        chdir: "/home/{{ gitlab_runner_user }}/"
      register: gitlab_runner_stop
      failed_when:
        - gitlab_runner_stop.rc != 0
      listen: "Restart gitlab-runner shell"

    # Register the gitlab runner with the gitlab server
    - name: Register the gitlab-runner shell
      ansible.builtin.command:
        cmd: "gitlab-runner register --non-interactive --url \"{{ gitlab_url }}/\" --token \"{{ gitlab_runner_executor_token }}\" --executor \"{{ gitlab_runner_executor_name }}\" --description \"{{ gitlab_runner_executor_name }}\" --tls-ca-file \"/home/{{ gitlab_runner_user }}/.gitlab-runner/certs/{{ gitlab_fqdn }}.crt\" --config \"/home/{{ gitlab_runner_user }}/.gitlab-runner/config.toml\""
        chdir: "/home/{{ gitlab_runner_user }}/"
      listen: "Restart gitlab-runner shell"

    - name: Install gitlab-runner shell
      ansible.builtin.command:
        cmd: "gitlab-runner install --user --config \"/home/{{ gitlab_runner_user }}/.gitlab-runner/config.toml\""
        chdir: "/home/{{ gitlab_runner_user }}/"
      listen: "Restart gitlab-runner shell"

    - name: Start gitlab-runner shell
      ansible.builtin.command:
        cmd: "gitlab-runner run --user --config \"/home/{{ gitlab_runner_user }}/.gitlab-runner/config.toml\""
        chdir: "/home/{{ gitlab_runner_user }}/"
      listen: "Restart gitlab-runner shell"

  become: true
  become_user: "{{ gitlab_runner_user }}"
