---
- name: Update dnf configuration
  community.general.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: max_parallel_downloads
    value: 10
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true

