---
- ansible.builtin.include_tasks: configure-yum-repos.yml
- ansible.builtin.include_tasks: install-yum-updates.yml
- ansible.builtin.include_tasks: install-dnf-automatic.yml

# Disable sleep for servers and workstations
- ansible.builtin.include_tasks: disable-sleep.yml
  when: ansible_host not in ["laptops"]
