---
- name: Install samba packages
  ansible.builtin.package:
    name:
      - samba
      - policycoreutils-python-utils
    state: latest
  become: true

- name: Ensure Samba is running and set to start at boot
  ansible.builtin.service:
    name: smb
    state: started
    enabled: true
  become: true

# Set up the samba user
- block:
  - name: Create samba users
    ansible.builtin.shell: >
      set -e -o pipefail
      && (pdbedit --user={{ samba_user }} 2>&1 > /dev/null)
      || (echo '{{ samba_password }}'; echo '{{ samba_password }}')
      | smbpasswd -s -a {{ samba_user }}
    args:
      executable: /bin/bash
    register: samba_create_users
    changed_when: "'Added user' in samba_create_users.stdout"
    no_log: true
    become: true

  - name: Set samba passwords
    ansible.builtin.shell: >
      set -e -o pipefail
      && (smbclient -U {{ samba_user }}%{{ samba_password }} -L 127.0.0.1 2>&1 > /dev/null)
      || (echo '{{ samba_password }}'; echo '{{ samba_password }}')
      | smbpasswd {{ samba_user }}
    args:
      executable: /bin/bash
    register: samba_verify_users
    changed_when: "'New SMB password' in samba_verify_users.stdout"
    no_log: true
    become: true

  - name: Enable samba user
    ansible.builtin.command: "smbpasswd -e {{ samba_user }}"
    register: samba_enable_user
    changed_when: "'Enabled user {{ samba_user }}' in samba_enable_user.stdout"
    become: true

# Set up the permissions on the samba folder
# NOTE: This folder must already exist, it could be mounted from a second drive, a zfs/btrfs array, etc.
# https://docs.fedoraproject.org/en-US/quick-docs/samba/
- block:
  - name: Change folder owner
    ansible.builtin.file:
      state: directory
      path: "{{ samba_folder }}"
      owner: "{{ samba_user }}"
      group: "{{ samba_user }}"
      mode: '0770'

  # semanage fcontext --add --type "samba_share_t" "/data1(/.*)?"
  - name: Allow sharing the folder
    community.general.sefcontext:
      path: "{{ samba_folder }}(/.*)?"
      setype: samba_share_t
      state: present

  # restorecon -R /data1
  - name: Apply new SELinux file context to filesystem
    ansible.builtin.command: "restorecon -R \"{{ samba_folder }}\""

  become: true

# NOTE: The share also seems to need at least one file within it or trying to read it from the client will fail with a lack of permissions

- name: Update samba configuration
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  notify:
    - Restart smb service

- name: Enable samba ports in firewall
  ansible.posix.firewalld:
    service: samba
    state: enabled
    immediate: true
    permanent: true
  become: true
