---
- hosts: podman
  roles:
    - podman

- hosts: gitlab
  roles:
    - podman_gitlab

- hosts: vaultwarden
  roles:
    - podman_vaultwarden

- hosts: homeassistant
  roles:
    - podman_home_assistant

- hosts: tandoor
  roles:
    - podman_tandoor
