---
# NOTE: This playbook is really only useful on a first deployment, call the individual plays in playbooks/podman/ to update individual services on later deployments

- hosts: podman
  roles:
    - podman

- ansible.builtin.import_playbook: podman/gitlab.yml
- ansible.builtin.import_playbook: podman/stirlingpdf.yml
- ansible.builtin.import_playbook: podman/vaultwarden.yml
- ansible.builtin.import_playbook: podman/homeassistant.yml
- ansible.builtin.import_playbook: podman/tandoor.yml
