---
- hosts: server
  roles:
    - fedora_common
    #- ntp
    - update_firmware

- hosts: gitlab_runner
  roles:
    - gitlab_runner

- hosts: sambaserver
  roles:
    - samba_server
  vars:
    samba_folder: "{{ fileserver_network_home_samba_folder }}"
    samba_user: "{{ fileserver_network_home_samba_username }}"
    samba_password: "{{ fileserver_network_home_samba_password }}"
