---
- hosts: linux
  roles:
    - fedora_common
    #- ntp
    - update_firmware

- ansible.builtin.import_playbook: service/syslog-ng.yml

- hosts: developer
  roles:
    - developer
    - vscodium

- hosts: desktop
  roles:
    - fedora_desktop
