---
# NOTE: This playbook is really only useful on a first deployment, call the individual plays in playbooks/service/ to update individual services on later deployments

- hosts: server
  roles:
    - fedora_common
    #- ntp
    - update_firmware

- ansible.builtin.import_playbook: service/gitlab_runner.yml
- ansible.builtin.import_playbook: service/samba_server.yml
